name: so_arm
services:
  so_arm:
    container_name: so_arm
    image: ghcr.io/ad-sdl/so_arm_module
    network_mode: host
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - path: .env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/so_arm_module:latest
        - ghcr.io/ad-sdl/so_arm_module:dev
    command: python -m so_arm_rest_node
    volumes:
      - ./settings.yaml:/home/madsci/settings.yaml
      - ./.madsci:/home/madsci/.madsci